version: '3'
services:
    www:
        build:
            context: ./www
            dockerfile: Dockerfile
        container_name: www
        env_file:
            - ./www/.env
        networks:
            - app-network
        ports:
            - 3000:3000

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: api
        networks:
            - app-network
        ports:
            - 4000:4000

networks:
    app-network:
        driver: bridge
