printWidth: 130
tabWidth: 4
semi: false
useTabs: false
singleQuote: true
trailingComma: all
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
requirePragma: false
singleAttributePerLine: false
quoteProps: as-needed
endOfLine: auto
plugins:
    - prettier-plugin-tailwindcss
