query EventConnection($limit: Int!, $nextPageCursor: Int, $eventStatus: EventStatusEnum, $direction: DirectionEnum) {
    eventConnection(limit: $limit, nextPageCursor: $nextPageCursor, eventStatus: $eventStatus, direction: $direction) {
        nodes {
            status
            latitude
            longitude
            direction
            date
            id
            persons {
                surname
                name
                secondName
                imageUrl
            }
            disappearedQty
            createdAt
        }
        pageInfo {
            limit
            nextPageCursor
        }
    }
}
