query GetAllEvents {
  eventConnection {
    nodes {
      status
      latitude
      longitude
      direction
      date
      id
      persons {
        surname
        name
        secondName
        imageUrl
      }
      disappearedQty
      createdAt
    }
    pageInfo {
      limit
      nextPageCursor
    }
  }
}