query Me {
    me {
        email
        userType
        fullName
        receiver {
            location
            phone
        }
        provider {
            location
            field
        }
        id
    }
}
