query PostConnection($limit: Int, $prevPageCursor: Int, $nextPageCursor: Int) {
    postConnection(limit: $limit, prevPageCursor: $prevPageCursor, nextPageCursor: $nextPageCursor) {
        nodes {
            title
            content
            imageUrl
            tags
            id
            authorId
            createdAt
        }
        pageInfo {
            limit
            hasNextPage
            hasPrevPage
            prevPageCursor
            nextPageCursor
        }
    }
}
